site_name: Codex CLI
plugins:
  - i18n:
      default_language: pt
      languages:
        - locale: pt
          name: Português
          default: true
          build: true
        - locale: en
          name: English
          build: true
nav:
  - Home: index.md
  - Índice Geral: indice_geral.md
  - Índice Visual: indice_visual.md
  - Checklist de PR: checklist_pr.md
  - Diário de Bordo: diario_de_bordo.md
  - Guia de Contribuição: guia_contribuicao.md
  - Configuração de API Keys: configuracao-api-keys.md
  - Guia Didático:
      - Auto Documentação de Ferramentas: guia_didatico/auto_documentacao_ferramentas.md
      - Como Escrever Testes: guia_didatico/como_escrever_testes.md
      - Ferramentas Externas: guia_didatico/ferramentas_externas.md
      - Como Ler Arquivos: guia_didatico/ler_arquivo.md
      - Percepção de Arquivos: guia_didatico/percepcao_arquivos.md
      - Pytest: guia_didatico/pytest.md
  - Roadmap: roadmap.md
  - Publicação PyPI/API: publicacao_pypi_api.md
  - Próxima Missão: proxima_missao.md
